apiVersion: apps/v1
kind: Deployment
metadata:
  name: springweb
spec:
  selector:
    matchLabels:
      app: springweb
  template:
    metadata:
      labels:
        app: springweb
    spec:
      containers:
      - name: spring-web
        image: kherguner/spring-web:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
